### ISSUE TITLE
How to install on HA 2021.7.3

### ISSUE THREAD

**Issue by KayIO** [carstenschroeder/elv_ws980wifi#1]
Hi !

I have a complete new install of HA 2021.7.3, but coudln' find any hint how to integrate the ELV WS980 WIFI into Home Assistant.
Do I have to edit the configuration.yaml ?
What are the entries?

Any hint would be apreciated.

Thanks a lot

**Comment by carstenschroeder** [comment]
Hi! You may install the component with HACS. Here are my configuration.yaml entries:

elv_ws980wifi:
  devices:
    - name: elv_weather_station
      host: 192.168.4.67
      port: 45000

sensor:
  - platform: elv_ws980wifi
    name: "in_temp"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi
    name: "out_temp"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi
    name: "dewpoint"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi
    name: "windchill"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi
    name: "heatindex"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi
    name: "in_humidity"
    unit_of_measurement: '%'

  - platform: elv_ws980wifi
    name: "out_humidity"
    unit_of_measurement: '%'

  - platform: elv_ws980wifi
    name: "abs_baro"
    unit_of_measurement: 'mbar'

  - platform: elv_ws980wifi
    name: "rel_baro"
    unit_of_measurement: 'mbar'

  - platform: elv_ws980wifi
    name: "wind_dir"
    unit_of_measurement: '°'

  - platform: elv_ws980wifi
    name: "wind_speed"
    unit_of_measurement: 'km/h'
    factor: 3.6

  - platform: elv_ws980wifi
    name: "gust_speed"
    unit_of_measurement: 'km/h'
    factor: 3.6

  - platform: elv_ws980wifi
    name: "rain_rate"
    unit_of_measurement: 'mm/h'

  - platform: elv_ws980wifi
    name: "rain_day"
    unit_of_measurement: 'mm'

  - platform: elv_ws980wifi
    name: "rain_week"
    unit_of_measurement: 'mm'

  - platform: elv_ws980wifi
    name: "rain_month"
    unit_of_measurement: 'mm'

  - platform: elv_ws980wifi
    name: "rain_year"
    unit_of_measurement: 'mm'

  - platform: elv_ws980wifi
    name: "rain_totals"
    unit_of_measurement: 'mm'

  - platform: elv_ws980wifi
    name: "light"
    unit_of_measurement: 'lux'

  - platform: elv_ws980wifi
    name: "uv"
    unit_of_measurement: 'W/m2'

  - platform: elv_ws980wifi
    name: "uvi"
    unit_of_measurement: ''

**Comment by carstenschroeder** [comment]
Hi! You may install the integration with HACS. Here are my configuration.yaml entries:

```yml
elv_ws980wifi:
  devices:
    - name: elv_weather_station
      host: '192.168.0.48'
      port: 45000

sensor:
  - platform: elv_ws980wifi
    name: "in_temp"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi
    name: "out_temp"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi
    name: "dewpoint"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi
    name: "windchill"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi
    name: "heatindex"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi
    name: "in_humidity"
    unit_of_measurement: '%'

  - platform: elv_ws980wifi
    name: "out_humidity"
    unit_of_measurement: '%'

  - platform: elv_ws980wifi
    name: "abs_baro"
    unit_of_measurement: 'mbar'

  - platform: elv_ws980wifi
    name: "rel_baro"
    unit_of_measurement: 'mbar'

  - platform: elv_ws980wifi
    name: "wind_dir"
    unit_of_measurement: '°'

  - platform: elv_ws980wifi
    name: "wind_speed"
    unit_of_measurement: 'km/h'
    factor: 3.6

  - platform: elv_ws980wifi
    name: "gust_speed"
    unit_of_measurement: 'km/h'
    factor: 3.6

  - platform: elv_ws980wifi
    name: "rain_rate"
    unit_of_measurement: 'mm/h'

  - platform: elv_ws980wifi
    name: "rain_day"
    unit_of_measurement: 'mm'

  - platform: elv_ws980wifi
    name: "rain_week"
    unit_of_measurement: 'mm'

  - platform: elv_ws980wifi
    name: "rain_month"
    unit_of_measurement: 'mm'

  - platform: elv_ws980wifi
    name: "rain_year"
    unit_of_measurement: 'mm'

  - platform: elv_ws980wifi
    name: "rain_totals"
    unit_of_measurement: 'mm'

  - platform: elv_ws980wifi
    name: "light"
    unit_of_measurement: 'lux'

  - platform: elv_ws980wifi
    name: "uv"
    unit_of_measurement: 'W/m2'

  - platform: elv_ws980wifi
    name: "uvi"
    unit_of_measurement: ''
```
