### ISSUE TITLE
sensor and device not showing up

### ISSUE THREAD

**Issue by doabigcheese** [carstenschroeder/elv_ws980wifi#5]
Hi,
i try to get the data into HA, but somehow its not working.
when i try to add the device somewhere in the lovelace UI, i can not find any elv_ws980wifi device...

Data is received:
`2022-08-02 13:59:43 DEBUG (SyncWorker_5) [custom_components.elv_ws980wifi] Updating...
2022-08-02 13:59:43 DEBUG (SyncWorker_5) [custom_components.elv_ws980wifi] sending 'ff ff 0b 00 06 04 04 19 (len=8)'
2022-08-02 13:59:43 DEBUG (SyncWorker_5) [custom_components.elv_ws980wifi] receiving...
2022-08-02 13:59:43 DEBUG (SyncWorker_5) [custom_components.elv_ws980wifi] received 'ff ff 0b 00 50 04 01 01 0e 02 01 1c 03 00 aa 04 01 1c 05 01 21 06 33 07 32 08 25 ca 09 25 ca 0a 00 aa 0b 00 00 0c 00 00 0e 00 00 00 00 10 00 00 00 00 11 00 00 00 5b 12 00 00 00 00 13 00 00 13 95 14 00 00 72 fb 15 00 04 f8 b2 16 03 10 17 02 31 bd (len=82)'
2022-08-02 13:59:43 DEBUG (SyncWorker_5) [custom_components.elv_ws980wifi] checksum '0x31'
2022-08-02 13:59:43 DEBUG (SyncWorker_5) [custom_components.elv_ws980wifi] checksum '0xBD'
2022-08-02 13:59:43 DEBUG (SyncWorker_5) [custom_components.elv_ws980wifi] in_temp: {'value': 27.0} (0x01)
2022-08-02 13:59:43 DEBUG (SyncWorker_5) [custom_components.elv_ws980wifi] out_temp: {'value': 28.4} (0x02)
2022-08-02 13:59:43 DEBUG (SyncWorker_5) [custom_components.elv_ws980wifi] dewpoint: {'value': 17.0} (0x03)`

any hints what am i missing`?
thnx

**Comment by carstenschroeder** [comment]
The name of the device is used as prefix of the sensors.  So if you use the example configuration the sensor names start with "elv_weather_station".

```
elv_ws980wifi:
  devices:
    - name: elv_weather_station        <<<<<<<<
      host: '192.168.0.2'
      port: 45000
sensor:
  - platform: elv_ws980wifi
    name: "in_temp"
    unit_of_measurement: '°C'

  - platform: elv_ws980wifi`
 ...
```
